services:
  db:
    image: postgres:16-alpine
    container_name: togglemaster_db
    environment:
      POSTGRES_USER: togglemaster
      POSTGRES_PASSWORD: togglemaster
      POSTGRES_DB: togglemaster_db
    ports:
      - "5432:5432"
    volumes:
      - togglemaster_db_data:/var/lib/postgresql/data
      - ./auth-service/db/init.sql:/docker-entrypoint-initdb.d/01-auth.sql:ro
      - ./flag-service/db/init.sql:/docker-entrypoint-initdb.d/02-flags.sql:ro
      - ./targeting-service/db/init.sql:/docker-entrypoint-initdb.d/03-targeting.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U togglemaster -d togglemaster_db"]
      interval: 5s
      timeout: 3s
      retries: 20

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth_service
    environment:
      PORT: "8001"
      MASTER_KEY: "admin-secreto-123"
      DATABASE_URL: "postgres://togglemaster:togglemaster@db:5432/togglemaster_db?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"
    restart: unless-stopped

  flag-service:
    build:
      context: ./flag-service
      dockerfile: Dockerfile
    container_name: flag_service
    environment:
      PORT: "8002"
      DATABASE_URL: "postgres://togglemaster:togglemaster@db:5432/togglemaster_db?sslmode=disable"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
    ports:
      - "8002:8002"
    restart: unless-stopped

  targeting-service:
    build:
      context: ./targeting-service
      dockerfile: Dockerfile
    container_name: targeting_service
    environment:
      PORT: "8003"
      DATABASE_URL: "postgres://togglemaster:togglemaster@db:5432/togglemaster_db?sslmode=disable"
      AUTH_SERVICE_URL: "http://auth-service:8001"
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
    ports:
      - "8003:8003"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: togglemaster_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  evaluation-service:
    build:
      context: ./evaluation-service
      dockerfile: Dockerfile
    container_name: evaluation_service
    environment:
      PORT: "8004"
      REDIS_URL: "redis://redis:6379"
      FLAG_SERVICE_URL: "http://flag-service:8002"
      TARGETING_SERVICE_URL: "http://targeting-service:8003"
      SERVICE_API_KEY: "tm_key_7e88f3adc588a03f31f9decb090244c2e5fac70b368aa69e8844677c16d05eb6"
      AWS_REGION: "${AWS_REGION}"
      AWS_SQS_URL: "${AWS_SQS_URL}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    depends_on:
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started
      flag-service:
        condition: service_started
      targeting-service:
        condition: service_started
    ports:
      - "8004:8004"
    restart: unless-stopped

  analytics-service:
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics_service
    environment:
      PORT: "8005"
      AWS_REGION: "${AWS_REGION}"
      AWS_SQS_URL: "${AWS_SQS_URL}"
      AWS_DYNAMODB_TABLE: "${AWS_DYNAMODB_TABLE}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      # Se você usa AWS Academy / credencial temporária:
      # AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
    ports:
      - "8005:8005"
    restart: unless-stopped
  
volumes:
  togglemaster_db_data:
