name: Auth Service CI-CD

on:
  push:
    branches: [ "main" ]
    paths:
      - "auth-service/**"
      - ".github/workflows/auth-service.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ vars.AUTH_ECR_REPOSITORY }}
  SERVICE_PATH: auth-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Download Go dependencies
        working-directory: ${{ env.SERVICE_PATH }}
        run: go mod tidy

      - name: Run Go tests
        working-directory: ${{ env.SERVICE_PATH }}
        run: go test ./...

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t $ECR_REPOSITORY:${{ steps.vars.outputs.short_sha }} \
            -f $SERVICE_PATH/Dockerfile \
            $SERVICE_PATH

      - name: Tag Docker image
        run: |
          docker tag \
            $ECR_REPOSITORY:${{ steps.vars.outputs.short_sha }} \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ steps.vars.outputs.short_sha }}

      - name: Push Docker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ steps.vars.outputs.short_sha }}
